using System.Collections;
using System.Collections.Generic;
using UnityEngine;
/*
*autor: Erick Hern치ndez silva
*Prueba si el collider est치 DENTRO o FUERA de una plataforma
*/
public class PruebaPiso : MonoBehaviour
{
    public static bool estaEnPiso = false;
    //Se ejecuta cuando el collider entra en contacto con otro collider
    private void OnTriggerEnter2D(Collider2D other)
    {
        if (other.gameObject.CompareTag("Map")){
            estaEnPiso = true;
            print("Est치 en piso");
        }
        
    }
    //Se ejecuta cuando el collider deja de tener contacto con otro collider
    private void OnTriggerExit2D(Collider2D other)
    {
        if (other.gameObject.CompareTag("Map")){
            estaEnPiso = false;
            print("No est치 en piso");
        }
    }
}
